name: test
on:
  push:
    branches:
      - main
    paths:
      - 'version.txt'
      - 'package.json'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Read Version File
        id: read_version_file
        uses: komorebitech/read-files-action@v1.5
        with:
          files: '["/version.txt"]'
          pattern: '/^version:/'
      - name: echo version
        run: |
          echo "${{ steps.read_version_file.outputs.content }}"
