name: test
on:
  push:
    branches:
      - main
    paths:
      - 'version.txt'
      - 'package.json'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Read Version File
        id: read_version_file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: echo version
        run: |
          echo "${{ steps.read_version_file.outputs.content }}"
