name: test
on:
  push:
    branches:
      - main
    #paths:
    #  - 'version.txt'
    #  - 'package.json'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: komorebitech/read-files-action@v1.5
        id: read_migration_files
        with:
          files: '["./version.txt"]'
          pattern: 'version'
      - name: prepare version
        id: GET_VERSION
        run: |
          echo VERSION=$(echo ${{ steps.read_migration_files.outputs.content }}) >> $GITHUB_ENV
      - name: echo version
        run: |
          echo "${{ env.VERSION }}"
