name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: my-runner
    steps:
      - name: read file
        id: file
        uses: juliangruber/read-file-action@v1.1.4
        with:
          context: .
          path: main.go
      - name: output
        run: |
          echo "output: {{ steps.file.outputs.content }}"
     
        
