name: go-docker
on: 
  push:
    branches:
      - main
    paths:
      - version.txt
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: komorebitech/read-files-action@v1.5
        id: read_migration_files
        with:
          files: '["./version.txt"]'
          pattern: 'version'
      - name: prepare version
        id: SET_VERSION
        run: |
          echo VERSION=$(echo "${{ steps.read_migration_files.outputs.content }}" | sed -n "/^version:/p" | cut -d ":" -f2 | awk '$1=$1') >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          tags: damocleses/wordle-server:${{ env.VERSION }}
      - name: check container exists
        id: container_exits
        run: echo '::set-output name=container::$((echo docker container ls --format "{{.Names}}" | sed -n "/wordle-server/p"))'
      - name: remove container
        if: ${{ steps.container_exits.outputs.container == 'wordle-server' }}
        run: |
          docker container stop wordle-server
          docker container rm wordle-server
      - name: Deploy
        run: |
          docker pull damocleses/wordle-server:${{ env.VERSION }}
          docker run -d --name wordle-server -p 7767:7767 damocleses/wordle-server:${{ env.VERSION }}
            
            
