name: go-docker
on: 
  push:
    branches:
      - main
    paths:
      - version.txt
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: komorebitech/read-files-action@v1.5
        id: read_migration_files
        with:
          files: '["./version.txt"]'
          pattern: 'version'
      - name: prepare version
        id: SET_VERSION
        run: |
          echo VERSION=$(echo "${{ steps.read_migration_files.outputs.content }}" | sed -n "/^version:/p" | cut -d ":" -f2 | awk '$1=$1') >> $GITHUB_ENV
      - name: push docker
        run: |
          docker build -t damocleses/wordle-server:${{ env.VERSION }} .
          docker push damocleses/wordle-server:${{ env.VERSION }}
      - name: check container exists
        id: container_exits
        run: |
          echo CONTAINER=$(docker container ls --format "{{.Names}}" | sed -n "/wordle-server/p" | awk '$1=$1') >> $GITHUB_ENV
      - name: echo container_exits
        run: echo ${{ env.CONTAINER }}
      - name: remove container
        if: ${{ env.CONTAINER }} == "wordle-server"
        run: |
          docker container stop wordle-server
          docker container rm wordle-server
      - name: Deploy
        run: |
          docker pull damocleses/wordle-server:${{ env.VERSION }}
          docker run -d --name wordle-server -p 7767:7767 damocleses/wordle-server:${{ env.VERSION }}
            
            
