name: go-docker
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check container exists
        id: container_exits
        run: echo '##[set-output name=container;]$((docker container ls --format "{{.Names}}" | sed -n "/wordle-server/p"))'
      - name: remove container
        if: ${{ steps.container_exits.outputs.container }} == 'wordle-server'
        run: |
          echo "${{ steps.container_exits.outputs.container }}"
          docker container stop wordle-server
          docker container rm wordle-server
      - name: Deploy
        run: |
          docker pull damocleses/wordle-server:${{ env.VERSION }}
          docker run -d --name wordle-server -p 7767:7767 damocleses/wordle-server:${{ env.VERSION }}
            
            
